# c:\projects\DNA-utils-universal\ystr_predictor\k8s\deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ystr-predictor
  labels:
    app: ystr-predictor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ystr-predictor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ystr-predictor
    spec:
      containers:
      - name: ystr-predictor
        image: user/ystr-predictor:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ystr-predictor-secrets
              key: secret-key
        volumeMounts:
        - name: models
          mountPath: /app/models
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ystr-predictor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ystr-predictor
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120

---
apiVersion: v1
kind: Service
metadata:
  name: ystr-predictor-blue
  labels:
    app: ystr-predictor
    color: blue
spec:
  selector:
    app: ystr-predictor
    color: blue
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ystr-predictor-green
  labels:
    app: ystr-predictor
    color: green
spec:
  selector:
    app: ystr-predictor
    color: green
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ystr-predictor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: predictor.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ystr-predictor-blue
            port:
              number: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard